### Deployment와 Service 포함
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  # Pods를 몇개 실행할지
  replicas: 1
  # Deployment 단계에서 구분하기 위한 Labels 설정
  selector:
    matchLabels:
      app: webapp
  # configuration for Pod
  template:
    metadata:
      # 동일한 Pod가 여러 개 생길 때 하나의 범주로 묶기 위해 Labels 설정
      labels:
        app: webapp
    spec:
      # 어떤 이미지를 불러올 것인지
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            # Node Port는 3000
            - containerPort: 3000
          env:
            # MongoDB와 연결하기
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  # webapp-config의 name과 동일하게
  name: webapp-service
spec:
  # outter service로 만들기(NodePort)
  type: NodePort
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      # port는 굳이 갖지 않아도 되는데 관습상 containerPort와 맞춤
      port: 3000
      # container Port와 같아야함.
      targetPort: 3000
      nodePort: 30100
