### Deployment와 Service 포함

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  # Pods를 몇개 실행할지
  replicas: 1
  # Deployment 단계에서 구분하기 위한 Labels 설정
  selector:
    matchLabels:
      app: mongo-express
  # configuration for Pod
  template:
    metadata:
      # 동일한 Pod가 여러 개 생길 때 하나의 범주로 묶기 위해 Labels 설정
      labels:
        app: mongo-express
    spec:
      # 어떤 이미지를 불러올 것인지
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            # MongoDB와 연결하기
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url

---
apiVersion: v1
kind: Service
metadata:
  # webapp-config의 name과 동일하게
  name: mongo-express-service
spec:
  # outter service로 만들기(NodePort)
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mongo-express
  ports:
    - protocol: TCP
      # port는 굳이 갖지 않아도 되는데 관습상 containerPort와 맞춤
      port: 8081
      # container Port와 같아야함.
      targetPort: 8081
      nodePort: 30000
